version: '3'

services:
  hugo:
    container_name: Hugo-blog
    image: peaceiris/hugo:latest
    ports:
      - 1313:1313
    volumes:
      - .:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
      - --minify
      - --buildFuture
      - -v